require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'assets/**/*'

Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

RSpec/ExampleLength:
  CountAsOne: [ 'array', 'hash', 'heredoc', 'method_call' ]

RSpec/MessageSpies:
  EnforcedStyle: receive
